### ISSUE TITLE
IP citation

### ISSUE THREAD

**Issue by yamatt** [DarrenRainey/Global-Masscan-Blacklist#1]
Hi, I wondered if it was possible to cite where the IP addresses came from, or what they relate to?

**Comment by DarrenRainey** [comment]
Sure but I need some clarifaction are you referring to the people/companys requesting to be blacklisted or the ip location i.e 127.0.0.1 localhost etc

**Comment by yamatt** [comment]
@DarrenRainey bit of both. Just the reasoning for being on the list. Rather than arbitrary IP addresses being added.

**Comment by DarrenRainey** [comment]
ok it'll take some work for me to find all the emails and add them but ill try and get it done later

**Comment by yamatt** [comment]
@DarrenRainey I wouldn't want to expose people reporting IPs they own if there are legitimite reasons behind it, and obviously there is a need to cover their privacy. The idea was more around identifing the legitimacy of an IP on this list. Perhaps in a categorisation form. For example:

- requested by {user}
- potential honeypot
- police/military IPs found from {url}

Not sure how appropriate that would be. But I have done similar just in commit messages.

**Comment by DarrenRainey** [comment]
Ok I get the idea and ill start sorting them on saturday

**Comment by DarrenRainey** [comment]
I've added a list of People/Places that wanted their IP blacklisted in a file named IP-Information.txt
